# NumPy  array operations

In [2]:
import numpy as np

In [9]:
# 1D array
arr = np.array([23,45,1,3,78,54,4,8,9,12])
print(arr)

[23 45  1  3 78 54  4  8  9 12]


In [39]:
# Multi-dimensional array:
arrmd = np.array([[1,2,3],[4,5,6]])
arrmd

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arrmd.dtype

dtype('int64')

#  Basic 1D Array Slicing 

In [12]:
# Syntax: arr[start : stop : step]

print(arr[:4])

[23 45  1  3]


In [13]:
print(arr[:])

[23 45  1  3 78 54  4  8  9 12]


In [14]:
print(arr[::2])

[23  1 78  4  9]


In [15]:
print(arr[-3:])

[ 8  9 12]


In [16]:
# reverse the slice
print(arr[-3:0:-1])

[ 8  4 54 78  3  1 45]


In [20]:
print(arr[-9:4:2])

[45  3]


In [21]:
print(arr[-4:4:2])

[]


#  Slicing in Multi-dimensional NumPy Arrays

In [42]:
arrmd

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print(arrmd[0:2:1])

[[1 2 3]
 [4 5 6]]


In [43]:
# Get all rows, first two columns
print(arrmd[:, 0:2])

[[1 2]
 [4 5]]


In [45]:
# Reverse all rows
print(arrmd[::-1,:])

[[4 5 6]
 [1 2 3]]


In [46]:
# Reverse all columns
print(arrmd[:,::-1])

[[3 2 1]
 [6 5 4]]


In [47]:
# Get diagonal elements
np.diag(arrmd)

array([1, 5])

In [49]:
# Get last row
arrmd[-1, :]

array([4, 5, 6])

# reshaping in NumPy array

In [52]:
arr1 = np.array([11, 2, 30, 42, 52, 6])
reshaped = arr1.reshape(2,3)
print(reshaped

[[11  2 30]
 [42 52  6]]


In [54]:
 # or arr2.flatten()
arr2 =  np.array([[11,2,30],[42,52,6]])
flattened = arr2.reshape(-1) 
print(flattened)

[11  2 30 42 52  6]


In [55]:
# Using -1 in reshape (Auto-calculate size)
reshaped = arr1.reshape(3, -1) 
print(reshaped)

[[11  2]
 [30 42]
 [52  6]]


In [56]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped = arr3.reshape(2, 2, 2)
print(reshaped)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Broadcasting

In [58]:
a = np.array([1, 2, 3])     
b = 1

result = a + b              
print(result)

[2 3 4]


In [60]:
c = np.array([[1, 2, 3]])     
d = np.array([[40],
              [20],
              [10]])         

result = c + d
print(result)

[[41 42 43]
 [21 22 23]
 [11 12 13]]


In [61]:
print(result + 10)

[[51 52 53]
 [31 32 33]
 [21 22 23]]
